services:
  caddy:
    extends:
      file: docker-compose.base.yaml
      service: caddy
    environment:
      - DISABLE_CADDY_PROD_SERVER=#

  clients:
    extends:
      file: docker-compose.base.yaml
      service: clients
    volumes:
      - ../../clients:/app/clients
    command: npm run dev
  
  services-api:
    extends:
      file: docker-compose.base.yaml
      service: services-api
    develop:
      watch:
        - action: sync+restart
          path: ../../dbs/main
          target: /app/dbs/main
          ignore:
            - data
        - action: sync+restart
          path: ../../saf-2025/lib/node-express
          target: /app/saf-2025/lib/node-express
        - action: sync+restart
          path: ../../specs/apis/dist
          target: /app/specs/apis/dist
        - action: sync+restart
          path: ../../saf-2025/lib/drizzle-sqlite3
          target: /app/saf-2025/lib/drizzle-sqlite3
        - action: sync+restart
          path: ../../services/api
          target: /app/services/api

  services-auth:
    extends:
      file: docker-compose.base.yaml
      service: services-auth
    develop:
      watch:
        - action: sync+restart
          path: ../../saf-2025/dbs/auth
          target: /app/dbs/auth
          ignore:
            - data
        - action: sync+restart
          path: ../../saf-2025/lib/node-express
          target: /app/lib/node-express
        - action: sync+restart
          path: ../../specs/apis/dist
          target: /app/specs/apis/dist
        - action: sync+restart
          path: ../../saf-2025/lib/drizzle-sqlite3
          target: /app/lib/drizzle-sqlite3
        - action: sync+restart
          path: ../../saf-2025/services/auth
          target: /app/services/auth

  specs-apis:
    extends:
      file: docker-compose.base.yaml
      service: specs-apis
    develop:
      watch:
        - action: sync+restart
          path: ./openapi.yaml
          target: /app/specs/apis/openapi.yaml

volumes:
  caddy_data:
  caddy_config: