# common elements between dev and test
services:
  caddy:
    image: caddy:2.9.1
    ports:
      - 80:80
    volumes:
      - ./remote-assets/config:/etc/caddy/
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - DOMAIN=${DOMAIN}
      - PROTOCOL=${PROTOCOL}
    depends_on:
      - clients

  clients:
    # Named for local dev, but doesn't get published; not needed for prod
    image: your-username-clients:latest
    build:
      context: ../..
      dockerfile: ./clients/Dockerfile

volumes:
  caddy_data:
  caddy_config:
