services:
  services-api:
    extends:
      file: remote-assets/docker-compose.prod.yaml
      service: services-api
    volumes: !override []
  services-auth:
    extends:
      file: remote-assets/docker-compose.prod.yaml
      service: services-auth
    volumes: !override []
  caddy:
    extends:
      file: remote-assets/docker-compose.prod.yaml
      service: caddy
    volumes: !override []
volumes:
  caddy_data:
  caddy_config:
