services:
  caddy:
    extends:
      file: docker-compose.base.yaml
      service: caddy
    environment:
      - DISABLE_CADDY_PROD_SERVER=#

  clients:
    extends:
      file: docker-compose.base.yaml
      service: clients
    volumes:
      - ../../clients:/app/clients
    command: npm run dev

volumes:
  caddy_data:
  caddy_config:
