services:
  specs-apis:
    build:
      context: ../..
      dockerfile: ./specs/apis/Dockerfile
    volumes:
      - ./dist:/app/specs/apis/dist
    develop:
      watch:
        - action: sync+restart
          path: ./openapi.yaml
          target: /app/specs/apis/openapi.yaml
    command: npm run generate-and-serve 